import { FaBolt, FaGraduationCap, FaLocationDot, FaRocket } from 'react-icons/fa6';
import { Seo } from '@/components/ui/Seo';
import { PageShell } from '@/components/ui/PageShell';
import { Section } from '@/components/ui/Section';
import { GlassCard } from '@/components/ui/GlassCard';
import { journey } from '@/data/content';

const facts = [{ icon: FaGraduationCap, label: 'Education', value: 'B.Tech CSE, 2025–29' }, { icon: FaLocationDot, label: 'Based in', value: 'Delhi NCR, India' }, { icon: FaBolt, label: 'Currently', value: '2nd-year CSE student' }, { icon: FaRocket, label: 'Seeking', value: 'Internship opportunities' }];
export default function About() { return <><Seo title="About" path="/about" /><PageShell><Section eyebrow="ABOUT ME" title="A student with a builder’s bias."><div className="grid gap-8 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-5 text-lg leading-8 text-muted"><p>I’m <strong className="font-semibold text-ink">Neil Dua</strong>, a Computer Science Engineering student at ABES Engineering College, Ghaziabad. I care about the satisfying middle ground between a hard technical problem and a simple experience for the person using it.</p><p>Right now, I’m turning classroom foundations into tangible projects: building interfaces, practicing data structures and algorithms, and steadily expanding into backend systems. I like work that is clear, collaborative, and a little ambitious.</p><p>My aim is straightforward: become the kind of engineer who can take a rough idea, ask the right questions, and help turn it into something people actually enjoy using.</p></div><div className="rounded-3xl border border-brand/20 bg-gradient-to-br from-brand/15 via-violet-500/10 to-transparent p-7"><p className="text-xs font-bold tracking-[.18em] text-brand">CURRENTLY EXPLORING</p><ul className="mt-5 space-y-4 text-sm text-ink"><li>↳ Clean React architectures</li><li>↳ DSA patterns & problem-solving</li><li>↳ Full-stack product thinking</li><li>↳ Systems that scale with care</li></ul></div></div></Section><Section eyebrow="THE PATH" title="A journey in motion."><ol className="relative ml-3 border-l border-line pl-8">{journey.map((item, index) => <li key={item.date} className="relative pb-10 last:pb-0"><span className="absolute -left-[41px] top-0 grid h-6 w-6 place-items-center rounded-full border-4 border-canvas bg-brand" /><p className="text-xs font-bold tracking-wider text-brand">{item.date}</p><h3 className="mt-2 font-display text-xl font-bold text-ink">{item.title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-muted">{item.copy}</p>{index === 1 && <span className="mt-3 inline-flex rounded-full border border-brand/20 bg-brand/10 px-2.5 py-1 text-xs font-semibold text-brand">You are here</span>}</li>)}</ol></Section><Section eyebrow="AT A GLANCE" title="The useful details."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{facts.map(({ icon: Icon, label, value }) => <GlassCard key={label} className="p-5"><Icon className="text-brand" /><p className="mt-5 text-xs font-bold uppercase tracking-wider text-muted">{label}</p><p className="mt-2 font-semibold leading-6 text-ink">{value}</p></GlassCard>)}</div></Section></PageShell></>; }
