import { type FormEvent, useState } from 'react';
import { FaArrowUpRightFromSquare, FaEnvelope, FaGithub, FaLinkedinIn, FaLocationDot, FaPaperPlane } from 'react-icons/fa6';
import { Seo } from '@/components/ui/Seo';
import { PageShell } from '@/components/ui/PageShell';
import { Section } from '@/components/ui/Section';
import { Button } from '@/components/ui/Button';
import { GlassCard } from '@/components/ui/GlassCard';
import { sendContactMessage } from '@/services/email';
import { siteConfig } from '@/lib/constants';
import { useUiStore } from '@/store/uiStore';

const initialForm = { name: '', email: '', message: '' };
export default function Contact() { const [form, setForm] = useState(initialForm); const [submitting, setSubmitting] = useState(false); const addToast = useUiStore((state) => state.addToast); const onSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (form.name.trim().length < 2 || !/^\S+@\S+\.\S+$/.test(form.email) || form.message.trim().length < 12) { addToast('error', 'Please add your name, a valid email, and a slightly longer message.'); return; } setSubmitting(true); try { await sendContactMessage(form); setForm(initialForm); addToast('success', 'Message sent — I’ll get back to you soon.'); } catch (error) { addToast('error', error instanceof Error ? error.message : 'Something went wrong. Please email me directly.'); } finally { setSubmitting(false); } };
  const cards = [{ icon: FaEnvelope, label: 'Email', value: siteConfig.email, href: `mailto:${siteConfig.email}` }, { icon: FaLinkedinIn, label: 'LinkedIn', value: 'linkedin.com/in/neil-dua', href: siteConfig.linkedin }, { icon: FaGithub, label: 'GitHub', value: 'github.com/Neil-166', href: siteConfig.github }];
  const mapUrl = import.meta.env.VITE_GOOGLE_MAPS_EMBED_URL as string | undefined;
  return <><Seo title="Contact" path="/contact" /><PageShell><Section eyebrow="CONTACT" title="Let’s make the next thing better." copy="Have an opportunity, an idea, or simply want to compare notes? My inbox is open."><div className="grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-4">{cards.map(({ icon: Icon, label, value, href }) => <a key={label} href={href} target={href.startsWith('http') ? '_blank' : undefined} rel="noreferrer" className="glass-card flex items-center gap-4 p-5 transition hover:border-brand/45"><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand/12 text-brand"><Icon /></span><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wider text-muted">{label}</p><p className="mt-1 truncate text-sm font-semibold text-ink">{value}</p></div><FaArrowUpRightFromSquare className="text-xs text-muted" /></a>)}<div className="overflow-hidden rounded-2xl border border-line bg-surface">{mapUrl ? <iframe title="Neil Dua location map" src={mapUrl} className="h-48 w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /> : <div className="flex min-h-48 flex-col justify-end bg-[radial-gradient(circle_at_70%_25%,rgb(119_140_255/.3),transparent_25%),linear-gradient(135deg,#10162d,#10131e)] p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10 text-brand"><FaLocationDot /></span><p className="mt-4 font-display text-lg font-bold text-ink">Delhi NCR, India</p><p className="mt-1 text-sm text-muted">Map embed ready — add the URL in your environment.</p></div>}</div></div><GlassCard hover={false} className="p-6 sm:p-8"><form onSubmit={onSubmit} className="space-y-5" noValidate><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold text-ink">Your name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="input" placeholder="Jane Smith" /></label><label className="grid gap-2 text-sm font-semibold text-ink">Email address<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="input" placeholder="jane@company.com" /></label></div><label className="grid gap-2 text-sm font-semibold text-ink">Tell me a little about it<textarea required rows={6} value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} className="input resize-y" placeholder="I’d love to talk about…" /></label><Button type="submit" disabled={submitting} className="w-full sm:w-auto">{submitting ? 'Sending…' : <><FaPaperPlane />Send message</>}</Button><p className="text-xs leading-5 text-muted">This form uses EmailJS. If it has not been configured yet, send a note directly to the email above.</p></form></GlassCard></div></Section></PageShell></>; }
