import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { FaArrowUpRightFromSquare, FaXmark } from 'react-icons/fa6';
import { Seo } from '@/components/ui/Seo';
import { PageShell } from '@/components/ui/PageShell';
import { Section } from '@/components/ui/Section';
import { technologies } from '@/data/skills';
import type { Technology } from '@/types';

export default function Explorer() { const [selected, setSelected] = useState<Technology | null>(null); return <><Seo title="Tech stack explorer" path="/explorer" /><PageShell><Section eyebrow="TECH STACK EXPLORER" title="The tools behind the experiments." copy="Tap into any technology to see how it fits into the way I think about building."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{technologies.map((technology) => { const Icon = technology.icon; return <button key={technology.name} onClick={() => setSelected(technology)} className="glass-card group p-6 text-left transition hover:border-brand/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/5 text-2xl" style={{ color: technology.color }}><Icon /></span><p className="mt-6 text-xs font-bold uppercase tracking-[.15em] text-muted">{technology.category}</p><div className="mt-2 flex items-center justify-between"><h2 className="font-display text-xl font-bold text-ink">{technology.name}</h2><FaArrowUpRightFromSquare className="text-muted transition group-hover:text-brand" /></div></button>; })}</div></Section></PageShell><AnimatePresence>{selected && <motion.div role="dialog" aria-modal="true" aria-label={`${selected.name} details`} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/75 p-5 backdrop-blur-sm" onClick={() => setSelected(null)}><motion.div initial={{ scale: .95, y: 12 }} animate={{ scale: 1, y: 0 }} exit={{ scale: .95, y: 12 }} onClick={(event) => event.stopPropagation()} className="w-full max-w-lg rounded-3xl border border-line bg-canvas p-7 shadow-2xl"><div className="flex items-start justify-between"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white/5 text-3xl" style={{ color: selected.color }}><selected.icon /></span><button onClick={() => setSelected(null)} className="grid h-9 w-9 place-items-center rounded-xl text-muted hover:bg-white/5 hover:text-ink" aria-label="Close technology details"><FaXmark /></button></div><p className="mt-6 text-xs font-bold uppercase tracking-[.15em] text-muted">{selected.category}</p><h2 className="mt-2 font-display text-3xl font-bold text-ink">{selected.name}</h2><p className="mt-4 leading-7 text-muted">{selected.description}</p><h3 className="mt-7 text-sm font-bold text-ink">How I use it</h3><ul className="mt-3 space-y-2">{selected.uses.map((use) => <li key={use} className="rounded-xl bg-white/[.04] px-4 py-3 text-sm text-muted">{use}</li>)}</ul></motion.div></motion.div>}</AnimatePresence></>; }
