import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { FaExpand, FaXmark } from 'react-icons/fa6';
import { Seo } from '@/components/ui/Seo';
import { PageShell } from '@/components/ui/PageShell';
import { Section } from '@/components/ui/Section';
import { galleryImages } from '@/data/content';

export default function Gallery() { const [active, setActive] = useState<number | null>(null); return <><Seo title="Gallery" path="/gallery" /><PageShell><Section eyebrow="GALLERY" title="A visual field of curiosity." copy="Snapshots of the technology, spaces, and energy behind the work."><div className="columns-1 gap-4 sm:columns-2 lg:columns-3">{galleryImages.map((image, index) => <button key={image.src} onClick={() => setActive(index)} className="group relative mb-4 block w-full overflow-hidden rounded-2xl text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"><img src={image.src} alt={image.alt} loading="lazy" className="w-full object-cover transition duration-500 group-hover:scale-[1.04]" /><span className="absolute inset-0 grid place-items-center bg-slate-950/0 text-white opacity-0 transition group-hover:bg-slate-950/35 group-hover:opacity-100"><span className="grid h-10 w-10 place-items-center rounded-full bg-white/15 backdrop-blur"><FaExpand /></span></span></button>)}</div></Section></PageShell><AnimatePresence>{active !== null && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} role="dialog" aria-modal="true" aria-label="Image preview" onClick={() => setActive(null)} className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/90 p-5 backdrop-blur"><button onClick={() => setActive(null)} className="absolute right-5 top-5 grid h-11 w-11 place-items-center rounded-xl bg-white/10 text-white" aria-label="Close preview"><FaXmark /></button><motion.img initial={{ scale: .96 }} animate={{ scale: 1 }} exit={{ scale: .96 }} onClick={(event) => event.stopPropagation()} src={galleryImages[active].src} alt={galleryImages[active].alt} className="max-h-[85vh] max-w-full rounded-2xl object-contain shadow-2xl" /></motion.div>}</AnimatePresence></>; }
