import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { FaChevronDown, FaCheck } from 'react-icons/fa6';
import { Seo } from '@/components/ui/Seo';
import { PageShell } from '@/components/ui/PageShell';
import { Section } from '@/components/ui/Section';
import { roadmap } from '@/data/content';

export default function Roadmap() { const [open, setOpen] = useState('DSA'); return <><Seo title="Learning roadmap" path="/roadmap" /><PageShell><Section eyebrow="LEARNING ROADMAP" title="A map, not a finish line." copy="Each track is intentionally staged: foundations first, then the useful complexity."><div className="space-y-3">{roadmap.map((item) => { const expanded = open === item.title; return <article key={item.title} className="overflow-hidden rounded-2xl border border-line bg-surface"><button onClick={() => setOpen(expanded ? '' : item.title)} aria-expanded={expanded} className="flex w-full items-center gap-4 p-5 text-left sm:p-6"><span className={`h-3 w-3 shrink-0 rounded-full bg-gradient-to-br ${item.accent} shadow-glow`} /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-4"><h2 className="font-display text-lg font-bold text-ink">{item.title}</h2><span className="text-sm font-bold text-ink">{item.completion}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/5"><div className={`h-full rounded-full bg-gradient-to-r ${item.accent}`} style={{ width: `${item.completion}%` }} /></div></div><FaChevronDown className={`shrink-0 text-muted transition ${expanded ? 'rotate-180' : ''}`} /></button><AnimatePresence>{expanded && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="border-t border-line px-6 pb-6 pt-5 sm:pl-14"><p className="max-w-2xl text-sm leading-6 text-muted">{item.detail}</p><div className="mt-5 grid gap-2 sm:grid-cols-3">{item.lessons.map((lesson) => <div key={lesson} className="flex items-center gap-2 rounded-xl bg-white/[.035] p-3 text-sm text-ink"><FaCheck className="text-xs text-brand" />{lesson}</div>)}</div></div></motion.div>}</AnimatePresence></article>; })}</div></Section></PageShell></>; }
